workdir: /data/iacobuzc/haochen/Tapestri_batch2/analysis/condor-pipeline
datasets:
  - M13
  - RA16_08
  # - BPA-2-IR
  # - BPA-3
  # - BPA-5-RSX

# ===== centralized data directory =====
raw_data_directory: /data/iacobuzc/haochen/Tapestri_batch2/batch2_data_compiled/fillout_h5
# this directory should be in the following structure:
#  - {patient_1}.*.h5
#  - {patient_2}.*.h5
annotated_mutations: /data/iacobuzc/haochen/Tapestri_batch2/batch2_data_compiled/manual_annotated_snv_lists
# this directory should be in the following structure:
#  - {patient_1}*voi.hz_curated.txt
#  - {patient_2}*voi.hz_curated.txt
falcon_solutions: /data/iacobuzc/haochen/Tapestri_batch2/batch2_data_compiled/falcon_results
# this directory should be in the following structure:
# - {patient_1}*assignment*.csv
# - {patient_1}*clone_profile*.csv
# - {patient_2}*assignment*.csv
# - {patient_2}*clone_profile*.csv
subclonal_mutations: /data/iacobuzc/haochen/Tapestri_batch2/analysis/condor-pipeline/manual_subclonal_snvs
# THIS PATH MUST EXIST, BUT NOT EVERY PATIENT MUST HAVE A FILE. But if there should be one, it should be named:
# - {patient_1}.subclonal_mutations.yaml

# ===== scripts and params =====
amplicon_coordinates_file: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/references/amplicon_panel.csv
condor_pipeline_scripts_dir: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/scripts
fast_condor_script: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/fast-ConDoR/src/fast-condor.py