workdir: /data/iacobuzc/haochen/condor_pipeline_trial
sample_name_map: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/Tapestri_batch2_samples_MASTER_INTERNAL.xlsx
patients:
  - M04
  - M07
  - M11
  - M12
  - M13
  - RA15_06
  - RA15_16
  - RA16_08
  - RA16_29
  - RA17_13
  - RA17_22
  - RA19_02
  - RA19_10
  - RA19_21
  - RA20_05
  - RA21_17
  - TP11
  - TP12
  - TP49
  - BPA-1
  - BPA-2
  - BPA-3
  - BPA-4
  - BPA-5

# ===== centralized data directory =====
raw_data_directory: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/fillout_h5
# this directory should be in the following structure:
#  - {patient_1}.*.h5
#  - {patient_2}.*.h5
annotated_mutations: /lila/data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/manual_annotated_snv_lists
# this directory should be in the following structure:
#  - {patient_1}*voi.hz_curated.txt
#  - {patient_2}*voi.hz_curated.txt
falcon_solutions: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/falcon_solutions
# this directory should be in the following structure:
# - {patient_1}*assignment*.csv
# - {patient_1}*clone_profile*.csv
# - {patient_2}*assignment*.csv
# - {patient_2}*clone_profile*.csv
subclonal_mutations: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/manual_subclonal_snvs
# THIS PATH MUST EXIST, BUT NOT EVERY PATIENT MUST HAVE A FILE. But if there should be one, it should be named:
# - {patient_1}.subclonal_mutations.yaml

# ===== scripts and params =====
amplicon_coordinates_file: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/references/panel3559_analysis.gene_cytoband.formatted.manual_adjusted.gene_pos_ado_added.csv
condor_pipeline_scripts_dir: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/scripts
fast_condor_script: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/fast-ConDoR/src/fast-condor.py
condor_downstream_scripts_dir: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/condor_downstream