workdir: /data/iacobuzc/haochen/Tapestri_batch2/analysis/condor-pipeline
datasets:
  - BPA-1
  # - BPA-2-IR
  - BPA-3

# ===== centralized data directory =====
raw_data_directory: /data/iacobuzc/haochen/Tapestri_batch2/batch2_data_BRCA_compiled/SNV_FILLOUT_results
# this directory should be in the following structure:
# - patient_1
#  - {patient_2}.*.h5
# - patient_2
#  - {patient_2}.*.h5
annotated_mutations: /data/iacobuzc/haochen/Tapestri_batch2/batch2_data_BRCA_compiled/manual_annotated_snv_lists
# this directory should be in the following structure:
#  - {patient_1}*voi.hz_curated.txt
#  - {patient_2}*voi.hz_curated.txt
readcount_directory: /data/iacobuzc/haochen/Tapestri_batch2/batch2_data_BRCA_compiled/raw_read_counts
# this directory should be in the following structure:
# - patient_1
#  - {patient_sample_1}.per_amplicon_read_counts.tsv
#  - {patient_sample_2}.per_amplicon_read_counts.tsv
# - patient_2
#  - {patient_2_sample_1}.per_amplicon_read_counts.tsv
#  - {patient_2_sample_2}.per_amplicon_read_counts.tsv
falcon_solutions: /data/iacobuzc/haochen/Tapestri_batch2/batch2_data_BRCA_compiled/falcon_solutions
# this directory should be in the following structure:
# - {patient_1}*assignment*.csv
# - {patient_1}*clone_profile*.csv
# - {patient_2}*assignment*.csv
# - {patient_2}*clone_profile*.csv
subclonal_mutations: /data/iacobuzc/haochen/Tapestri_batch2/analysis/condor-pipeline/manual_subclonal_snvs
# THIS PATH MUST EXIST, BUT NOT EVERY PATIENT MUST HAVE A FILE. But if there should be one, it should be named:
# - {patient_1}.subclonal_mutations.yaml

# ===== scripts and params =====
amplicon_coordinates_file: /home/zhangh5/work/Tapestri_batch2/analysis/full-ConDoR/references/amplicon_panel.csv
condor_pipeline_scripts_dir: /home/zhangh5/work/Tapestri_batch2/analysis/full-ConDoR/scripts
fast_condor_script: /home/zhangh5/work/Tapestri_batch2/analysis/full-ConDoR/fast-ConDoR/src/fast-condor.py

# nclones:
#     - 2
#     - 3
#     - 4
#     - 5
#     - 6
#     - 7
#     - 8
#     - 9
#     - 10